### ISSUE TITLE
From reviewing code not live experience: Hard coded to 10 virtual GPU's?

### ISSUE THREAD

**Issue by jake-brewer-isa** [grgalex/nvshare#17]
It looks like there is a hard coded limit at 10 virtual GPU's.

When multi-GPU support is added, will this work well and add value to a 12 GPU machine?

kubernetes/manifests/device-plugin.yaml:64-65
```
- name: NVSHARE_VIRTUAL_DEVICES
          value: "10"
```

**Comment by grgalex** [comment]
`NVSHARE_VIRTUAL_DEVICES` represents the amount of `nvshare.com/gpu` devices that the device plugin advertizes to kubelet for each physical GPU that it manages.

For the time being, it only manages 1 physical GPU per node. So this value means that this GPU has 10 "slots" for containers.
